name: marvel_characters
description: List of Marvel characters
version: 0.0.1
publish_to: none

environment:
  sdk: ^3.8.1

resolution: workspace

dev_dependencies:
  auto_route_generator:
  barrel_files:
  build_runner:
  freezed:
  injectable_generator:
  json_serializable:
  retrofit_generator: