name: _
publish_to: none
environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^10.1.2
  flutter_bloc:
  freezed_annotation:
  flow_builder:
  barrel_files_annotation:
  get_it:
  asn1lib:
  crypto:
  dio:
  dio_http2_adapter:
  injectable:
  json_annotation:
  retrofit:
  tide_prelude:
    path: ./utility/tide_prelude
  tide_di:
    path: ./utility/tide_di

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator:
  barrel_files:
  build_runner:
  injectable_generator:
  json_serializable:
  retrofit_generator:
  tide_analysis:
    path: ./utility/tide_analysis

workspace:
    - app/miniclient
    - utility/tide_design_system
    - utility/tide_prelude
    - utility/tide_di
    - utility/tide_analysis
    - utility/api_client
    - utility/feature_flow
    - feature/marvel_characters
    - feature/marvel_details